// Generated by CoffeeScript 2.0.2
(function() {
  var Mset, dicts, m;

  dicts = require("./dicts");

  Mset = class Mset {
    constructor(...items) {
      var i, j, len;
      this.d = new dicts.Dict();
      for (j = 0, len = items.length; j < len; j++) {
        i = items[j];
        this.d.set(i, this.d.get(i, 0) + 1);
      }
    }

    toString() {}

  };

  m = new Mset(1, 2, 2, 3);

  console.log(m);

}).call(this);

//# sourceMappingURL=multisets.js.map
